LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := RemovePackages
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES := AmbientSensePrebuilt AppDirectedSMSService
LOCAL_OVERRIDES_PACKAGES += Photos
LOCAL_OVERRIDES_PACKAGES += DevicePolicyPrebuilt Drive
LOCAL_OVERRIDES_PACKAGES += DiagnosticsToolPrebuilt Maps
LOCAL_OVERRIDES_PACKAGES += MicropaperPrebuilt
LOCAL_OVERRIDES_PACKAGES += Photos PixelWallpapers2021
LOCAL_OVERRIDES_PACKAGES += PixelLiveWallpaperPrebuilt
LOCAL_OVERRIDES_PACKAGES += PrebuiltGmail
LOCAL_OVERRIDES_PACKAGES += RecorderPrebuilt ScribePrebuilt
LOCAL_OVERRIDES_PACKAGES += Showcase SoundAmplifierPrebuilt
LOCAL_OVERRIDES_PACKAGES += arcore
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
